### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by erskck1** [NuttyLogic/BSBolt#102]
Hi, 

I get an error after running the following command. 

**Command :** 

**python3 -m  BSBolt Align -DB** mouse_ref **-F1** Sample_R1.fastq.gz **-F2** Sample_R2.fastq.gz **-O** output_prefix **-M**              **-t** 10

**Error:** 

alignment failed, check options
Traceback (most recent call last):
  File ".../anaconda3/envs/bsbolt/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".../anaconda3/envs/bsbolt/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".../anaconda3/envs/bsbolt/lib/python3.8/site-packages/BSBolt/__main__.py", line 27, in <module>
    launch_bsb()
  File ".../anaconda3/envs/bsbolt/lib/python3.8/site-packages/BSBolt/__main__.py", line 23, in launch_bsb
    launcher(arguments)
  File ".../anaconda3/envs/bsbolt/lib/python3.8/site-packages/BSBolt/Utils/Launcher.py", line 107, in launch_alignment
    align_bisulfite(bwa_cmd, arguments.O)
  File ".../anaconda3/envs/bsbolt/lib/python3.8/site-packages/BSBolt/Utils/Launcher.py", line 47, in align_bisulfite
    mapping_stats = process_mapping_statistics(bs_alignment.mapping_statistics)
  File ".../anaconda3/envs/bsbolt/lib/python3.8/site-packages/BSBolt/Utils/Launcher.py", line 55, in process_mapping_statistics
    **mappability = (mapping_dict['TotalAlignments'] - mapping_dict['Unaligned']) / mapping_dict['TotalAlignments']
ZeroDivisionError: division by zero**
.../anaconda3/envs/bsbolt/lib/python3.8/site-packages/BSBolt/External/BWA/bwa mem -Y -M -A 1 -B 4 -D 0.5 -E 1,1 -L 30,30 -T 10 -U 17 -W 0 -c 500 -d 100 -k 19 -m 50 -r 1.5 -t 10 -w 100 -y 20 -O 6,6 -h 100,200 -e 0.1 -l 0.5 -n 5 -Z 0.95 BSB_ref.fa Sample_R1.fastq.gz Sample_R2.fastq.gz
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 666668 sequences (100000200 bp)...
[M::process] read 666668 sequences (100000200 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 253394, 4, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (315, 369, 427)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (91, 651)
[M::mem_pestat] mean and std.dev: (371.49, 88.15)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 763)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
Alignment Complete: Time 0:02:15

Is this problem due to my data or is it in the program?

Best regards.

**Comment by NuttyLogic** [comment]
The ZeroDivisionError is being thrown due to the alignment not being properly counted. This is either due to a bug or a no valid read alignments. Are there reads in the output alignment file? Also, could you try running the command without the **-M** option?

I fixed the ZeroDivisionError and bumped the version to 1.3.6. Now zero mappability will be returned without throwing an error.
