### ISSUE TITLE
provide intermediate results on mappability

### ISSUE THREAD

**Issue by antonkulaga** [NuttyLogic/BSBolt#108]
I see that bsbolt is very sensitive to parameters and input data while the time required to process the whole dataset can be >10 hours It would be nice if it will output to stdout intermediate results for mappability so I can stop the pipeline if I see that intermediate mappability is zero.

**Comment by NuttyLogic** [comment]
This should be straightforward to implement. I'll add it as a ToDo for the next release.

**Comment by NuttyLogic** [comment]
Implemented in v1.4.6
