### ISSUE TITLE
Could not retrieve index file for .bam

### ISSUE THREAD

**Issue by VitaminBrad** [NuttyLogic/BSBolt#127]
Hello,

When running 

`python3 -m bsbolt CallMethylation -I BSBolt_output/SRP097629/Alignment_test.bam -O ~/tests/BSB_pe_test -DB ~/tests/TestData/BSB_Test_DB -t 2 `

I get the following error:

> [E::idx_find_and_load] Could not retrieve index file for 'BSBolt_output/SRP097629/Alignment_test.bam'
[E::hts_idx_push] NO_COOR reads not in a single block at the end 29 -1
[E::sam_index] Read 'SRR5195621.2' with ref_name='NC_000079.6', ref_length=120421639, flags=67, pos=89576430 cannot be indexed
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/bsbolt/CallMethylation/ProcessMethylationContigs.py", line 70, in __init__
    self.input_bam = pysam.Samfile(input_file, 'rb', require_index=True)
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 1007, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] No such file or directory

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/root/.local/lib/python3.7/site-packages/bsbolt/__main__.py", line 27, in <module>
>     launch_bsb()
>   File "/root/.local/lib/python3.7/site-packages/bsbolt/__main__.py", line 23, in launch_bsb
>     launcher(arguments)
>   File "/root/.local/lib/python3.7/site-packages/bsbolt/Utils/Launcher.py", line 138, in launch_methylation_call
>     bedgraph_output=arguments.BG)
>   File "/root/.local/lib/python3.7/site-packages/bsbolt/CallMethylation/ProcessMethylationContigs.py", line 73, in __init__
>     pysam.index(input_file)
>   File "/root/.local/lib/python3.7/site-packages/pysam/utils.py", line 75, in __call__
>     stderr))
> pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools index: failed to create index for "BSBolt_output/SRP097629/Alignment_test.bam"\n'

Could this be because the 
1. Sequences were not trimmed,
2. Bad quality reads, or
3. It has nothing to do with BSBolt & everything to do with samtools ?

Thanks!

**Comment by VitaminBrad** [comment]
Running

`samtools sort BSBolt_output/test.bam -o BSBolt_output/test.sorted.bam`

gave me 

`[E::idx_find_and_load] Could not retrieve index file for 'BSBolt_output/test.sorted.bam'
Processing Contigs: 100%|███████████████████████| 47/47 [00:15<00:00,  3.06it/s]`

Save to say fixed?

**Comment by NuttyLogic** [comment]
Is the alignment file position sorted when calling methylation? 

The matrix aggregation command expects at least 2 files, the command is being interpreted as a line separated list of CGmap files. The command should work for your test if you run 

```shell
python3 -m bsbolt AggregateMatrix -F BSBolt_output/test.CGmap,BSBolt_output/test.CGmap -O BSBolt_output/test_matrix.txt
```

**Comment by VitaminBrad** [comment]
Rearrangements along these lines fixed the issue. 

Thank you (and for the wonderful platform)!
