### ISSUE TITLE
Mapping to original bottom strand

### ISSUE THREAD

**Issue by SLundregan** [NuttyLogic/BSBolt#128]
During read alignment of my single end, directional RRBS data I noticed that ~50% or reads mapped to Watson C2T while ~50% mapped to Crick C2T. However, it is my understanding that reads originating from the original bottom strand should map to Crick G2A, and Crick C2T should represent reads complementary to original bottom. Is there something I'm missing here?

I have run through the provided test example and can confirm that all reads map either Watson C2T or Crick C2T:

python3 -m bsbolt Index -G ~/tests/TestData/BSB_test.fa -DB ~/tests/TestData/BSB_Test_DB 
python3 -m bsbolt Simulate -G ~/tests/TestData/BSB_test.fa -O ~/tests/TestSimulations/BSB_up
python3 -m bsbolt Align -DB ~/tests/TestData/BSB_Test_DB -F1 ~/tests/TestSimulations/BSB_up_1.fq -O ~/tests/BSB_up_test

# Clipped output:

[main] Real time: 23.105 sec; CPU: 22.961 sec
Alignment Complete: Time 0:00:23
------------------------------
Total Reads: 313856
Mappability: 100.000 %
------------------------------
Reads Mapped to Watson_C2T: 156914
Reads Mapped to Crick_C2T: 156942
Reads Mapped to Watson_G2A: 0
Reads Mapped to Crick_G2A: 0
------------------------------
Unmapped Reads (Single / Paired Ends): 0
Bisulfite Ambiguous: 0

**Comment by NuttyLogic** [comment]
For a single end directional library you expect to only observe C2T conversion events in the first read (and G2A in the second for paired reads), so alignment output looks correct.

**Comment by SLundregan** [comment]
Ah okay, I see. Thanks for clearing that up.
