### ISSUE TITLE
Alignment for fasta ? 

### ISSUE THREAD

**Issue by hmyh1202** [NuttyLogic/BSBolt#132]
I  have had test the software using fasta file. However it report error  such as :

[M::mem_process_seqs] Processed 148150 reads in 261.581 CPU sec, 132.685 real sec
[E::sam_parse1] SEQ and QUAL are of different length
[W::sam_read1] Parse error at line 153
truncated file.

my  fasta file is as normal fasta file and check passed.

**Comment by NuttyLogic** [comment]
Fasta alignment isn't supported with BSBolt.
