### ISSUE TITLE
conda install of BSBolt issue

### ISSUE THREAD

**Issue by boconnell89** [NuttyLogic/BSBolt#135]
I installed BSbolt via conda, but ran into the following issue:
```
bsbolt Index -G /mnt/e/refs/mm10/mm10.fa -DB /mnt/e/refs/mm10/ -IA
/home/oconnelb/anaconda3/lib/python3.8/site-packages/bsbolt/External/BWA/bwa: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/oconnelb/anaconda3/lib/python3.8/site-packages/bsbolt/External/BWA/bwa)
```

Looking online, this seems to be a result of when the BWA install was compiled?

In any case, building from the github still seems to work alright.

**Comment by NuttyLogic** [comment]
I'll see if we can address this with the next release

**Comment by hnikaein** [comment]
Another walkthrough is to compile the bwa from the source inside the bsbolt and replace the binary.
