### ISSUE TITLE
Write output to stdout [Feature Request]

### ISSUE THREAD

**Issue by boconnell89** [NuttyLogic/BSBolt#136]
It would be extremely useful if there was an option to write to stdout for pipelining purposes.

I figure a flag  that when called either changes:
https://github.com/NuttyLogic/BSBolt/blob/84a1adbbd8dd602e382b93f7b55053cf2fd6101e/bsbolt/Align/AlignReads.py#L49

to something like
`bam_compression = subprocess.Popen([stream_bam, '-@', str(self.output_threads), '-o', '/dev/stdout'],` or something similar.

or just has uncompressed header and SAM format reads written to stdout (would be the fastest for pipelines, since it skips compression/decompression entirely).

**Comment by NuttyLogic** [comment]
Implemented output to stdout in 1.6.0
