### ISSUE TITLE
BSBolt Align err

### ISSUE THREAD

**Issue by PengpengGuan** [NuttyLogic/BSBolt#138]
When we run the BSBolt to align reads to reference genome. We find an error, the information as follow:

/public/home/ppguan/soft/miniconda/miniconda2/envs/python3.6/lib/python3.6/site-packages/bsbolt/External/BWA/bwa mem -Y -A 1 -B 4 -D 0.5 -E 1,1 -L 30,30 -T 10 -U 17 -W 0 -c 500 -d 100 -k 19 -m 50 -r 1.5 -t 1 -w 100 -y 20 -O 6,6 -h 100,200 -e 0.1 -l 0.5 -n 5 -Z 0.95 ./BSBolt_index/hg19.fa ./SRR5392315_head1M_1.cut2.fastq
['/public/home/ppguan/soft/miniconda/miniconda2/envs/python3.6/lib/python3.6/site-packages/bsbolt/External/BWA/bwa', 'mem', '-Y', '-A', '1', '-B', '4', '-D', '0.5', '-E', '1,1', '-L', '30,30', '-T', '10', '-U', '17', '-W', '0', '-c', '500', '-d', '100', '-k', '19', '-m', '50', '-r', '1.5', '-t', '1', '-w', '100', '-y', '20', '-O', '6,6', '-h', '100,200', '-e', '0.1', '-l', '0.5', '-n', '5', '-Z', '0.95', './BSBolt_index/hg19.fa', './SRR5392315_head1M_1.cut2.fastq']
/public/home/ppguan/soft/miniconda/miniconda2/envs/python3.6/lib/python3.6/site-packages/bsbolt/External/BWA/bwa: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /public/home/ppguan/soft/miniconda/miniconda2/envs/python3.6/lib/python3.6/site-packages/bsbolt/External/BWA/bwa)
/public/home/ppguan/soft/miniconda/miniconda2/envs/python3.6/lib/python3.6/site-packages/bsbolt/External/BWA/bwa: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /public/home/ppguan/soft/miniconda/miniconda2/envs/python3.6/lib/python3.6/site-packages/bsbolt/External/BWA/bwa)
1
Traceback (most recent call last):
  File "/public/home/ppguan/soft/miniconda/miniconda2/envs/python3.6/bin/BSBolt", line 11, in <module>
    sys.exit(launch_bsb())
  File "/public/home/ppguan/soft/miniconda/miniconda2/envs/python3.6/lib/python3.6/site-packages/bsbolt/__main__.py", line 23, in launch_bsb
    launcher(arguments)
  File "/public/home/ppguan/soft/miniconda/miniconda2/envs/python3.6/lib/python3.6/site-packages/bsbolt/Utils/Launcher.py", line 110, in launch_alignment
alignment failed, check options
    align_bisulfite(bwa_cmd, arguments.O, arguments.OT)
  File "/public/home/ppguan/soft/miniconda/miniconda2/envs/python3.6/lib/python3.6/site-packages/bsbolt/Utils/Launcher.py", line 43, in align_bisulfite
    bs_alignment.align_reads()
  File "/public/home/ppguan/soft/miniconda/miniconda2/envs/python3.6/lib/python3.6/site-packages/bsbolt/Align/AlignReads.py", line 70, in align_reads
    raise BisulfiteAlignmentError
bsbolt.Align.AlignReads.BisulfiteAlignmentError

Through we find the error when we build index for reference genome, it looks like that we get the refernece index. However, the align commnd can not run it successfuly. So could you help me to sovle this problem, Thanks a lot.

**Comment by NuttyLogic** [comment]
The aligner didn't compile correctly for your environment. Building the BSBolt from source should solve this issue
