### ISSUE TITLE
List of methylated sites from simulated reads

### ISSUE THREAD

**Issue by RenzoTale88** [NuttyLogic/BSBolt#139]
Hello,
maybe I'm just missing this option, so apologies if it is my mistake, but is there an option when simulating BS-reads to save the positions and level of methylation of the sites in the reference genome? I can see the cigar that contains the information, but it would be handy toi have a function that extracts that automatically.

Thanks in advance
Andrea

EDIT: I can see that there are the `_variants.pkl`, `.pkl` and `_values.pkl` files, but I can't find a documentation to detail their contents.

**Comment by NuttyLogic** [comment]
Hi Andrea,

You're correct, the aggregate data is contained in the pickled files. I described the format of the three files below. All three are pickled python dictionaries. 

.pkl – Describe the per contig simulated methylation values for each site.

`{site: (Strand(0 positive, 1 negative), methylation values (0-1), CG site(0- No 1-Yes)) }`

values.pkl – Describe simulated read coverage levels 

`{‘chr:pos’, [methylated_bases, unmethylated_bases]}`

variant.pkl – Per contig simulation variants

```
Pos: {'chrom': contig,
  'pos': pos,
  'reference': reference base,
  'alt': alt base IUPAC,
  'heterozygous': bool,
  'indel': indel size if present,
  'iupac': (iupac bases )}
```

**Comment by RenzoTale88** [comment]
@NuttyLogic Thank you for the explanation, one more question: some sites have the position naming only, whereas other have some sites in them (e.g. `'4836_T_G': (1, 4.129303457598266e-12, 0)`). Does this refer to the variants, to errors or both?

**Comment by NuttyLogic** [comment]
That refers to the methylation status of a variant site. In the example you provided, the methylation values  of a negative strand t to g variant. The coordinates are zero based.
