### ISSUE TITLE
Simulation Result

### ISSUE THREAD

**Issue by JunxiFeng** [NuttyLogic/BSBolt#140]
Hello,

I am an undergraduate student using BSBolt's simulation functionality, and this might be a silly question: the results I got are the pickle files as follows, but I was expecting to get paired-end fastq files so that I can use them for alignment later on. Am I doing something wrong here? Thank you so much!

<img width="1039" alt="Screen Shot 2023-01-04 at 12 53 27 AM" src="https://user-images.githubusercontent.com/60299660/210518374-ee2f7e70-3fcc-4c81-bced-e1f75f756259.png">

**Comment by NuttyLogic** [comment]
The pickle files contain summary information about the simulated read sites. There should also be fastq files if the simulation finished correctly.
