### ISSUE TITLE
Using The CGmap withiout creating the Aggregationmatrix

### ISSUE THREAD

**Issue by olaraym** [NuttyLogic/BSBolt#148]
Hello @NuttyLogic 

Thanks for the wonderful and easy-to-implement program. I am currently using this package however I have just one sample which was sequenced paired-End. The CGmap I obtained from the Methylation call process contains both forward and reverse methylation probability for each context. Please which of the stand information should be used in the downstream analysis. If both strands are informative, How can I make sense of the methylation probability for each Cytosine position from both strand information? Thanks.

**Comment by NuttyLogic** [comment]
Hello @olaraym,

Both strands should provide information in both single and paired end sequencing in the absence of a capture bias. Could you provide an example of the CGmap output?

**Comment by olaraym** [comment]
Hi @NuttyLogic

Thanks for the response, below is part of an output I got

scaffold_1      C       23111   CG      CG      0.95122 39      41

scaffold_1      G       23112   CG      CG      1.0     27      27

scaffold_1      C       23203   CG      CG      0.953488        41      43

scaffold_1      G       23204   CG      CG      1.0     47      47

scaffold_1      C       23216   CG      CG      0.97619 41      42

scaffold_1      G       23217   CG      CG      0.977778        44      45

scaffold_1      C       23222   CG      CG      0.976744        42      43

scaffold_1      G       23223   CG      CG      1.0     42      42

scaffold_1      C       23235   CG      CG      1.0     40      40

scaffold_1      G       23236   CG      CG      0.954545        42      44

scaffold_1      C       23248   CG      CG      0.944444        34      36

scaffold_1      G       23249   CG      CG      0.97561 40      41

scaffold_1      C       23495   CG      CG      1.0     37      37

scaffold_1      G       23496   CG      CG      0.958333        46      48

scaffold_1      C       23542   CG      CG      0.95    38      40

scaffold_1      G       23543   CG      CG      1.0     47      47

scaffold_1      C       23701   CG      CG      1.0     23      23

scaffold_1      G       23702   CG      CG      0.947368        18      19

scaffold_1      C       23708   CG      CG      1.0     25      25

scaffold_1      G       23709   CG      CG      0.952381        20      21

**Comment by olaraym** [comment]
Another question is; what is the stipulated cut-off for a position being methylated or unmethylated? 

Thanks.

**Comment by NuttyLogic** [comment]
Could you provide the alignment command and provide detail on how the index was created?  The cutoff is based on the called base, with a mapping quality and base call quality filter. So a C in a sequencing read originating from the + strand would be considered methylated provided it based the quality filters.

**Comment by olaraym** [comment]
Thanks @NuttyLogic for your assistance. Below are the commands I used after running a quality check using fastqc and fortunately no need for trimming adaptors;

1. Index generation for the reference genome
Command: python3 -m bsbolt Index -G /path/to/reference.fas -DB /path/to/saveoutput
2. Read alignment of the obtained fastq  file (PE reads) to the indexed reference
Command:  python3 -m bsbolt Align -DB path/to/previous_output -F1 input1.fastq -F2 input2.fastq -O ./output -t 20
3. Methylation calling pre-processing
	a. fixmates to prepare for duplicate removal, using -p to display proper pair check
	command: samtools fixmate -p -m input.bam out.fixmate.bam
	b. Sort the output by coordinate for duplicate calling
	command: samtools sort -@ 20 -o wgbs_sorted.bam out.fixmate.bam
	c. removal of duplicates
	command: samtools markdup wgbs_sorted.bam wgbs_dup.bam
	d. Indexing the dup bam file
	samtools index wgbs_dup.bam
4. BSBolt CallMethylation
command: python3 -m bsbolt CallMethylation -I wgbs_dup.bam -O  wgbs_out -DB ../ -t 20 -verbose > wgbs_meth_stat

Then the wgbs_out file has the output as 

scaffold_1   C   23111   CG   CG   **0.95**   39   41
scaffold_1   G   23112   CG   CG   **1.0**     27   27
scaffold_1   C   23203   CG   CG   **0.95**   41   43
scaffold_1   G   23204   CG   CG   **1.0**     47   47
scaffold_1   C   23216   CG   CG   **0.97**   41   42
scaffold_1   G   23217   CG   CG   **0.97**   44   45
scaffold_1   C   23222   CG   CG   **0.97**   42   43
scaffold_1   G   23223   CG   CG   **1.0**     42   42
scaffold_1   C   23235   CG   CG   **1.0**     40   40
scaffold_1   G   23236   CG   CG   **0.95**   42   44

Note that these positions for some scaffolds do not appear on both strands so I converted all G positions to C positions by subtracting 1 from it and I removed duplicate positions and kept just one position for each CG site on the scaffold.

My concern as I mentioned earlier is that is there a particular probability score to conclude that a position is truly methylated or not considering the fact that not all positions that were called are either 0 or 1 but in the range between 0 and 1.

I hope to get your thoughts on this.

Thanks once again for your help.

**Comment by NuttyLogic** [comment]
Yes, all of the positions are called as either zero or 1, depending on the reported base in the read. There isn't a probability associated with the reported call per se, just a filtering threshold based on mapping quality and base call quality. The reported beta value in the CGmap files is the methylated bases / the total number of bases. Looking at these data it appear that these are CGC sites, where a CG site encountered on both strands.

**Comment by olaraym** [comment]
Thanks, @NuttyLogic for the response.

Does this mean that any other beta value apart from 0 (i.e. no methylated bases/total number of bases) and 1 (i.e. all base methylated/total number of bases) are not supposed to be considered as being methylated and are to be discarded? For instance, there are some reads where the beta values are 0.2 and some are 0.5 how will these be classified (methylated or unmethylated)?

**Comment by NuttyLogic** [comment]
The beta value is a per site metric, a beta value of .5 would mean half the reads aligning over that site have a methylated base and the other half have an unmethylated base
