### ISSUE TITLE
Aligning G2A single read

### ISSUE THREAD

**Issue by boconnell89** [NuttyLogic/BSBolt#149]
There does not seem to be a way to align a single read explicitly with G2A coversion.  I need to align my paired reads separately as they are bisulfite converted HiC, and bwa mem does not handle the long insert distances well. I've found that the second read will automatically be assumed to have C2T coversion if presented as -F1.

Is there a way to do this currently? I was thinking that maybe a combination of -UN and -SP might force it to consider G2A preferentially?

**Comment by NuttyLogic** [comment]
Your suggestion of combining -UN and -SP will preferentially align G2A. The default  -SP value, 0.1, should be reasonable.

**Comment by boconnell89** [comment]
I tried this, and with -SP 0.25, I get only about 0.3% of reads aligning C2T, which is fine for my purposes.
