### ISSUE TITLE
Can the software Bsbolt build the mm10 database?

### ISSUE THREAD

**Issue by heweihuang** [NuttyLogic/BSBolt#151]
After running the Bsbolt index command for a day, the mm10 database is still not established, After the bwa index command is used to create the database, the sa file is stuck

[bwt_gen] Finished constructing BWT in 614 iterations.
[bwa_index] 1979.83 seconds elapse.
[bwa_index] Update BWT... 23.93 sec
[bwa_index] Pack forward-only FASTA... 11.86 sec
[bwa_index] Construct SA from BWT and Occ...

**Comment by NuttyLogic** [comment]
Could you provide the command you used to generate the index?

**Comment by heweihuang** [comment]
> After running the Bsbolt index command for a day, the mm10 database is still not established, After the bwa index command is used to create the database, the sa file is stuck
> 
> [bwt_gen] Finished constructing BWT in 614 iterations. [bwa_index] 1979.83 seconds elapse. [bwa_index] Update BWT... 23.93 sec [bwa_index] Pack forward-only FASTA... 11.86 sec [bwa_index] Construct SA from BWT and Occ...
